#!/usr/bin/bash

input="$1"

results=$(grep 'results' $input)
watch=$(awk -F= '/watch/{print $2}' $input | tr '\n' ',' | sed 's/,$//')

url="http://www.youtube.com/watch_videos?video_ids=$watch"
(echo $url; echo $results)| xsel -ib
printf "$url\n\n$results"
